

const products = [
    {name:"Tecno Spark 4", price:600,image:"/images/pic (1).jpg"},
    {name:"Tecno Spark 4", price:550,image:"/images/pic (2).jpg"},
    {name:"Tecno Spark 4", price:450,image:"/images/pic (3).jpg"},
    {name:"Tecno Spark 4", price:550,image:"/images/pic (4).jpg"},
    {name:"Tecno Spark 5", price:500,image:"/images/pic (5).jpg"},
    {name:"infinix smart 6", price:800,image:"/images/pic (6).jpg"},
    {name:"infinix smart 6plus", price:900,image:"/images/pic (7).jpg"},
    {name:"infinix smart 6", price:2500,image:"/images/pic (8).jpg"},
    {name:"infinix smart 6plus", price:900,image:"/images/pic (9).jpg"},
    {name:"infinix smart 6", price:600,image:"/images/pic (10).jpg"},
    {name:"infinix smart 5", price:750,image:"/images/pic (11).jpg"},
    {name:"infinix smart 5", price:800,image:"/images/pic (12).jpg"},
    {name:"Itel P17", price:450,image:"/images/pic (13).jpg"},
    {name:"Itel P17", price:400,image:"/images/pic (14).jpg"},
    {name:"Itel P17", price:400,image:"/images/pic (15).jpg"},
    {name:"Itel P17", price:400,image:"/images/pic (16).jpg"},
    {name:"Tecno pop5", price:550,image:"/images/pic (17).jpg"},
    {name:"Tecno pop5", price:550,image:"/images/pic (18).jpg"},
    {name:"Tecno pop5", price:550,image:"/images/pic (19).jpg"},
    {name:"Tecno pop5", price:550,image:"/images/pic (20).jpg"},
    {name:"Tecno pop5", price:550,image:"/images/pic (21).jpg"},
    {name:"Tecno pop5", price:550,image:"/images/pic (22).jpg"},
    {name:"Tecno pop5", price:550,image:"/images/pic (23).jpg"},
    {name:"Tecno pop5", price:550,image:"/images/pic (24).jpg"},
    {name:"Tecno pop5", price:550,image:"/images/pic (25).jpg"},
    {name:"Tecno spark 9t", price:1100,image:"/images/pic (26).jpg"},
    {name:"Tecno spark 9t", price:1100,image:"/images/pic (27).jpg"},
    {name:"Tecno spark 9t", price:1100,image:"/images/pic (28).jpg"},
    {name:"Tecno spark 9t", price:1100,image:"/images/pic (29).jpg"},
    {name:"Tecno spark 9t", price:1100,image:"/images/pic (30).jpg"},
    {name:"Tecno spark 9t", price:1100,image:"/images/pic (31).jpg"},
    {name:"Tecno camon ", price:2500,image:"/images/pic (1).jpg"},
    {name:"Tecno camon ", price:2500,image:"/images/pic (1).jpg"},
]

export default products